### PR TITLE
Enable SWIG Python threading support

### LINKED ISSUE #49: callback system crashing kernel with subclassed `MMEventCallback`
Hi,

I'm using an Olympus IX83 microscope with `pymmcore-plus`. In https://github.com/tlambert03/pymmcore-plus/issues/21 I found what I thought were issues with pymmcore-plus but on further inspection seem to be issues with pymmcore itself (or perhaps the secret olympus driver). 

On this microscope if I register a pure `pymmcore.MMEventCallback` and then do `setConfig` then there is no issue and it prints out all the callbacks to the terminal (Though there is some multiple calling of callbacks perhaps)
(These prints come from here: https://github.com/micro-manager/mmCoreAndDevices/blob/97f82b9ef02788d8b6e9aa70283eb10c7c645a6e/MMCore/MMEventCallback.h)
```
onPropertyChanged() Core Shutter Shutter-1
onPropertyChanged() DiaShutter State 1
onConfigGroupChanged() Channel BF
onPropertyChanged() TransmittedIllumination 1 Brightness 100 
onConfigGroupChanged() Channel BF
onPropertyChanged() EpiShutter 1 State 0
onConfigGroupChanged() Channel BF 
```

However if I switch to using a subclass of that object that doesn't introduce any changes then my python immediately crashes with no error messages printed anywhere I can see:

```python
class MyCallbacks(pymmcore.MMEventCallback):
    def __init__(self):
        super().__init__()

# cb = pymmcore.MMEventCallback()
cb = MyCallbacks()
mmcore.registerCallback(cb)
```

I only see this crash when changing the config, if I do something like set the `X` position then the callback works the same as the pymmcore version.

This is deeply confusing because I thought that subclassing an object like that should be exactly the same as having the same object. However in https://github.com/tlambert03/pymmcore-plus/issues/21#issuecomment-881701240 it was suggested that this may be an incompatibiliity due to nuances with swig:

> it's possible that the callback system is subtly incompatible with the SwigPyObject wrapping pymmcore.MMEventCallback (see here for a bit more, and note that pymmcore currently uses the -builtin flag) but that's just a guess.

Any help getting to the bottom of this issue would be greatly appreciated.

### PR DESCRIPTION
**Pull request by ianhi**
Maybe fixes #49 
Opening a PR to have github actions action build the wheel so I can try it out.

### CODE REVIEW

**Comment by marktsuchida** [comment]
Mind if I change this to use `%module("threads"=1)` inside the `.i` file instead of relying on command line args? Mostly because I think it's an inherent requirement for the wrapper rather than a build configuration.

**Comment by ianhi** [comment]
> Mind if I change this to use %module("threads"=1) inside the .i file instead of relying on command line args? Mostly because I think it's an inherent requirement for the wrapper rather than a build configuration.

Please go for whatever you think is best! I'm happy to close this if you have a better option as well.

**Comment by marktsuchida** [comment]
@ianhi Great, I just pushed to your branch (sorry for the CI noise it may have created on your fork). I think this should be merged whether or not it fully fixes #49, but I'll wait for you to give it a try, just in case there are any surprises.

**Comment by ianhi** [comment]
@marktsuchida 🎉 🎉 🎉 it does indeed fix #49 🎉 🎉 🎉

**Comment by tlambert03** [comment]
amazing!!  great job!

**Pull request merged**
