### PR TITLE
Build wheels for 3.9

### PR DESCRIPTION
**Pull request by tlambert03**
Hi @marktsuchida @nicost, would love to have py3.9 wheels for pymmcore on pypi.  Wheels built and worked fine for me locally on mac 10.15 and 11.1 with py3.9.1, and they appear to be [building fine on CI](https://github.com/tlambert-forks/pymmcore/actions/runs/548460189) in this PR.

It's not clear to me from the github workflow how you're actually deploying to PyPI (i.e. whether you're manually using twine?).  I could try to set up an auto-deploy action here too... but you'd need to add your twine API key to the repo secrets.  (or, if you prefer to just upload manually that's fine too).

thanks

### CODE REVIEW

**Comment by marktsuchida** [comment]
Thanks for testing this, @tlambert03.
I can squash & merge this if you make these changes:
- Please make it so that your PR doesn't revert the Ubuntu build test versions (looks like you did this while I was writing this comment!)
- The NumPy version used for Python 3.9 needs to be newer; please see `maintainer-notes.md` for how to determine the correct version

Deployment is manual, and I think I want to keep it that way for now, because things can go wrong so easily with this build.

**Comment by marktsuchida** [comment]
Also,
- The manylinux build also need to build for 3.9

**Comment by tlambert03** [comment]
thanks, updated.

**Comment by marktsuchida** [comment]
Thanks, @tlambert03. I'll create a release for this shortly.

**Comment by tlambert03** [comment]
thanks @marktsuchida!

**Pull request merged**
